### ISSUE TITLE
deploy alpha release 后，无信息通知我默认用户名和密码

### ISSUE THREAD

**Issue by Pancongwen** [MatchboxDorry/dorry-platform-backend#4]
**Version**
Alpha Release

**What I have done**
Deploy alpha  release

**Expect Result**
Tell me the default username and password

**Actual Result**
I don't know the username and password
![screenshot from 2017-04-12 10-39-14](https://cloud.githubusercontent.com/assets/25834392/24938851/4a9b9646-1f6c-11e7-86ce-dd7f3dfb558b.png)

**Comment by DawnTan-0321** [comment]
The issue has been solved,close.
